Исправлены некоторые недочеты в ЛР6
Lyncore/edu_osis_lab6 pull request #6
Opened 2024-11-11 08:17 UTC by tretdm

2024-11-11 08:19 UTC, tretdm commented on df/tretdm/gethomepasswd.sh
> +    ls -l /home/$1
Это по стандарту FHS. https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

2024-11-11 08:37 UTC, Lyncore requested changes

2024-11-11 08:37 UTC, Lyncore commented on df/tretdm/arithmetic.sh
Тут же правильно было

2024-11-11 08:37 UTC, Lyncore commented on df/tretdm/avg.sh
А вот здесь как раз нужно было реализовать перебор аргументов через цикл

2024-11-11 08:37 UTC, Lyncore commented on df/tretdm/gethomepasswd.sh
> +    ls -l /home/$1
Ок

2024-11-12 10:00 UTC, Lyncore approved these changes

2024-11-12 11:52 UTC, tretdm commented
когда merge

2024-11-13 07:13 UTC, merged